### ISSUE TITLE
Kubernetes Installation on VMs with Multiple Network Interfaces

### ISSUE THREAD

**Issue by nyukeit** [lerndevops/educka#12]
The scripts for installation work really well however, for initialising a Kubernetes cluster, you should probably mention the importance of `--apiserver-advertise-address` and `--pod-network-cidr`. 

After following the instructions verbatim, my Vagrant VM cluster often fails at Worker Node Pre-Flight check to join cluster because, what I assume is, it is not able to find the API Server address, because the CNI defaults to `eth0` but should be on `eth1`.

**Comment by leaddevops** [comment]
sure nyukeit, definitely will update the things
