### ISSUE TITLE
The CNI

### ISSUE THREAD

**Issue by marviigrey** [lerndevops/educka#9]
Firstly, I noticed that there was a change in the CNI, moving from weave to calico. This didn't solve my network issue still,i think there's a
misconfiguration somewhere in other files cause i keep on receiving localhost 8080 refused meanwhile my instanc has port 8080 open,everyother thing is ready and ctive except the CNI.

https://vimeo.com/756761294/1936d67043

NAME               STATUS     ROLES                  AGE   VERSION
ip-172-31-90-156   NotReady   control-plane,master   15m   v1.23.10
ubuntu@ip-172-31-90-156:~$
ubuntu@ip-172-31-90-156:~$ sudo kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
ubuntu@ip-172-31-90-156:~$ kubectl get nodes
NAME               STATUS     ROLES                  AGE   VERSION
ip-172-31-90-156   NotReady   control-plane,master   21m   v1.23.10

**Comment by leaddevops** [comment]
the issue is solved nwo
